//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace GMXHelper
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailParameters", Namespace="http://schemas.datacontract.org/2004/07/GMXHelper")]
    public partial class MailParameters : object
    {
        
        private string[] BCCField;
        
        private string BodyField;
        
        private string[] CCField;
        
        private GMXHelper.FilePropertiesManager[] FilesField;
        
        private string[] FromField;
        
        private string FromNameField;
        
        private string PassField;
        
        private int PortField;
        
        private System.Net.Mail.MailPriority PriorityField;
        
        private string SubjectField;
        
        private string[] ToField;
        
        private string UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BCC
        {
            get
            {
                return this.BCCField;
            }
            set
            {
                this.BCCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GMXHelper.FilePropertiesManager[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromName
        {
            get
            {
                return this.FromNameField;
            }
            set
            {
                this.FromNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass
        {
            get
            {
                return this.PassField;
            }
            set
            {
                this.PassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port
        {
            get
            {
                return this.PortField;
            }
            set
            {
                this.PortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Net.Mail.MailPriority Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilePropertiesManager", Namespace="http://schemas.datacontract.org/2004/07/GMXHelper")]
    public partial class FilePropertiesManager : object
    {
        
        private string errorsField;
        
        private string fileNameField;
        
        private long lengthField;
        
        private byte[] streamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] stream
        {
            get
            {
                return this.streamField;
            }
            set
            {
                this.streamField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Section", Namespace="http://schemas.datacontract.org/2004/07/GMXHelper")]
    public partial class Section : object
    {
        
        private string CSSFontField;
        
        private int ColumnsField;
        
        private string HeaderTextField;
        
        private int PageOnInsertField;
        
        private int PageOnInsertXField;
        
        private int PageOnInsertYField;
        
        private string[] TableContentField;
        
        private string TextField;
        
        private bool onlyNewPageField;
        
        private bool rBottomField;
        
        private bool rLeftField;
        
        private bool rRightField;
        
        private bool rTopField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSSFont
        {
            get
            {
                return this.CSSFontField;
            }
            set
            {
                this.CSSFontField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Columns
        {
            get
            {
                return this.ColumnsField;
            }
            set
            {
                this.ColumnsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeaderText
        {
            get
            {
                return this.HeaderTextField;
            }
            set
            {
                this.HeaderTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageOnInsert
        {
            get
            {
                return this.PageOnInsertField;
            }
            set
            {
                this.PageOnInsertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageOnInsertX
        {
            get
            {
                return this.PageOnInsertXField;
            }
            set
            {
                this.PageOnInsertXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageOnInsertY
        {
            get
            {
                return this.PageOnInsertYField;
            }
            set
            {
                this.PageOnInsertYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] TableContent
        {
            get
            {
                return this.TableContentField;
            }
            set
            {
                this.TableContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool onlyNewPage
        {
            get
            {
                return this.onlyNewPageField;
            }
            set
            {
                this.onlyNewPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool rBottom
        {
            get
            {
                return this.rBottomField;
            }
            set
            {
                this.rBottomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool rLeft
        {
            get
            {
                return this.rLeftField;
            }
            set
            {
                this.rLeftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool rRight
        {
            get
            {
                return this.rRightField;
            }
            set
            {
                this.rRightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool rTop
        {
            get
            {
                return this.rTopField;
            }
            set
            {
                this.rTopField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentPDF", Namespace="http://schemas.datacontract.org/2004/07/GMXHelper")]
    public partial class DocumentPDF : object
    {
        
        private bool IsCotizacionField;
        
        private string PVLID4CondGralesField;
        
        private string PageFootField;
        
        private float PageFootxField;
        
        private bool PageNumField;
        
        private bool ProtectCopyField;
        
        private string StaticCSSField;
        
        private string StaticTextField;
        
        private int StaticXPositionField;
        
        private int StaticYPositionField;
        
        private byte[] TemplateField;
        
        private byte[] TemplateOverField;
        
        private byte[] WatermarkField;
        
        private float mBottomField;
        
        private float mLeftField;
        
        private float mRightField;
        
        private float mTopField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCotizacion
        {
            get
            {
                return this.IsCotizacionField;
            }
            set
            {
                this.IsCotizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PVLID4CondGrales
        {
            get
            {
                return this.PVLID4CondGralesField;
            }
            set
            {
                this.PVLID4CondGralesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageFoot
        {
            get
            {
                return this.PageFootField;
            }
            set
            {
                this.PageFootField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PageFootx
        {
            get
            {
                return this.PageFootxField;
            }
            set
            {
                this.PageFootxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PageNum
        {
            get
            {
                return this.PageNumField;
            }
            set
            {
                this.PageNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProtectCopy
        {
            get
            {
                return this.ProtectCopyField;
            }
            set
            {
                this.ProtectCopyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaticCSS
        {
            get
            {
                return this.StaticCSSField;
            }
            set
            {
                this.StaticCSSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaticText
        {
            get
            {
                return this.StaticTextField;
            }
            set
            {
                this.StaticTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaticXPosition
        {
            get
            {
                return this.StaticXPositionField;
            }
            set
            {
                this.StaticXPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaticYPosition
        {
            get
            {
                return this.StaticYPositionField;
            }
            set
            {
                this.StaticYPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Template
        {
            get
            {
                return this.TemplateField;
            }
            set
            {
                this.TemplateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] TemplateOver
        {
            get
            {
                return this.TemplateOverField;
            }
            set
            {
                this.TemplateOverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Watermark
        {
            get
            {
                return this.WatermarkField;
            }
            set
            {
                this.WatermarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float mBottom
        {
            get
            {
                return this.mBottomField;
            }
            set
            {
                this.mBottomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float mLeft
        {
            get
            {
                return this.mLeftField;
            }
            set
            {
                this.mLeftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float mRight
        {
            get
            {
                return this.mRightField;
            }
            set
            {
                this.mRightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float mTop
        {
            get
            {
                return this.mTopField;
            }
            set
            {
                this.mTopField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Destinatario", Namespace="http://schemas.datacontract.org/2004/07/GMXHelper")]
    public partial class Destinatario : object
    {
        
        private string DomicilioField;
        
        private string MailField;
        
        private string NombreField;
        
        private string RFCField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domicilio
        {
            get
            {
                return this.DomicilioField;
            }
            set
            {
                this.DomicilioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmisionPago", Namespace="http://schemas.datacontract.org/2004/07/GMXHelper")]
    public partial class EmisionPago : object
    {
        
        private string AutorizacionField;
        
        private string CCTypeField;
        
        private System.Nullable<System.DateTime> FechaEmisionField;
        
        private string FolioCPagosField;
        
        private string FormaPagoField;
        
        private string FriendlyResponseField;
        
        private double ImportePagoField;
        
        private int MonedaField;
        
        private string NombreTHField;
        
        private string PolizaField;
        
        private string ReferenciaField;
        
        private string TarjetaField;
        
        private string URLField;
        
        private byte[] WatermarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autorizacion
        {
            get
            {
                return this.AutorizacionField;
            }
            set
            {
                this.AutorizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCType
        {
            get
            {
                return this.CCTypeField;
            }
            set
            {
                this.CCTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEmision
        {
            get
            {
                return this.FechaEmisionField;
            }
            set
            {
                this.FechaEmisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioCPagos
        {
            get
            {
                return this.FolioCPagosField;
            }
            set
            {
                this.FolioCPagosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaPago
        {
            get
            {
                return this.FormaPagoField;
            }
            set
            {
                this.FormaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyResponse
        {
            get
            {
                return this.FriendlyResponseField;
            }
            set
            {
                this.FriendlyResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImportePago
        {
            get
            {
                return this.ImportePagoField;
            }
            set
            {
                this.ImportePagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTH
        {
            get
            {
                return this.NombreTHField;
            }
            set
            {
                this.NombreTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Poliza
        {
            get
            {
                return this.PolizaField;
            }
            set
            {
                this.PolizaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia
        {
            get
            {
                return this.ReferenciaField;
            }
            set
            {
                this.ReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tarjeta
        {
            get
            {
                return this.TarjetaField;
            }
            set
            {
                this.TarjetaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Watermark
        {
            get
            {
                return this.WatermarkField;
            }
            set
            {
                this.WatermarkField = value;
            }
        }
    }
}
namespace System.Net.Mail
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailPriority", Namespace="http://schemas.datacontract.org/2004/07/System.Net.Mail")]
    public enum MailPriority : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGMXITService")]
public interface IGMXITService
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGMXITService/SendMail", ReplyAction="http://tempuri.org/IGMXITService/SendMailResponse")]
    System.IAsyncResult BeginSendMail(GMXHelper.MailParameters mail, System.AsyncCallback callback, object asyncState);
    
    bool EndSendMail(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGMXITService/GenerateDocument", ReplyAction="http://tempuri.org/IGMXITService/GenerateDocumentResponse")]
    System.IAsyncResult BeginGenerateDocument(GMXHelper.Section[] Sections, GMXHelper.DocumentPDF DocPdf, System.AsyncCallback callback, object asyncState);
    
    byte[] EndGenerateDocument(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGMXITService/DistribuirDocumentacionPoliza", ReplyAction="http://tempuri.org/IGMXITService/DistribuirDocumentacionPolizaResponse")]
    System.IAsyncResult BeginDistribuirDocumentacionPoliza(
                string MailType, 
                bool oficinaMex, 
                string PVL, 
                string NoPoliza, 
                GMXHelper.Destinatario[] asegurado, 
                GMXHelper.Destinatario[] agente, 
                GMXHelper.Destinatario[] suscriptor, 
                GMXHelper.Destinatario[] nicho, 
                GMXHelper.Destinatario[] DDP, 
                GMXHelper.FilePropertiesManager archivoCotizacion, 
                GMXHelper.FilePropertiesManager folletoCotizacion, 
                GMXHelper.FilePropertiesManager caratulaPoliza, 
                GMXHelper.FilePropertiesManager slipCompra, 
                GMXHelper.FilePropertiesManager controlPago, 
                GMXHelper.FilePropertiesManager condicionesGenerales, 
                GMXHelper.FilePropertiesManager[] FolletoPoliza, 
                System.AsyncCallback callback, 
                object asyncState);
    
    bool EndDistribuirDocumentacionPoliza(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGMXITService/GenerateRecibo", ReplyAction="http://tempuri.org/IGMXITService/GenerateReciboResponse")]
    System.IAsyncResult BeginGenerateRecibo(GMXHelper.EmisionPago emisionPago, System.AsyncCallback callback, object asyncState);
    
    byte[] EndGenerateRecibo(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGMXITService/savePolicyFiles", ReplyAction="http://tempuri.org/IGMXITService/savePolicyFilesResponse")]
    System.IAsyncResult BeginsavePolicyFiles(string condGralesNombre, byte[] condGrales, string condPartNombre, byte[] condPart, string numeroPolizaPVL, System.AsyncCallback callback, object asyncState);
    
    bool EndsavePolicyFiles(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGMXITServiceChannel : IGMXITService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SendMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public SendMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GenerateDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GenerateDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public byte[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DistribuirDocumentacionPolizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public DistribuirDocumentacionPolizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GenerateReciboCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GenerateReciboCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public byte[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class savePolicyFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public savePolicyFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GMXITServiceClient : System.ServiceModel.ClientBase<IGMXITService>, IGMXITService
{
    
    private BeginOperationDelegate onBeginSendMailDelegate;
    
    private EndOperationDelegate onEndSendMailDelegate;
    
    private System.Threading.SendOrPostCallback onSendMailCompletedDelegate;
    
    private BeginOperationDelegate onBeginGenerateDocumentDelegate;
    
    private EndOperationDelegate onEndGenerateDocumentDelegate;
    
    private System.Threading.SendOrPostCallback onGenerateDocumentCompletedDelegate;
    
    private BeginOperationDelegate onBeginDistribuirDocumentacionPolizaDelegate;
    
    private EndOperationDelegate onEndDistribuirDocumentacionPolizaDelegate;
    
    private System.Threading.SendOrPostCallback onDistribuirDocumentacionPolizaCompletedDelegate;
    
    private BeginOperationDelegate onBeginGenerateReciboDelegate;
    
    private EndOperationDelegate onEndGenerateReciboDelegate;
    
    private System.Threading.SendOrPostCallback onGenerateReciboCompletedDelegate;
    
    private BeginOperationDelegate onBeginsavePolicyFilesDelegate;
    
    private EndOperationDelegate onEndsavePolicyFilesDelegate;
    
    private System.Threading.SendOrPostCallback onsavePolicyFilesCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public GMXITServiceClient()
    {
    }
    
    public GMXITServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GMXITServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GMXITServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GMXITServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<SendMailCompletedEventArgs> SendMailCompleted;
    
    public event System.EventHandler<GenerateDocumentCompletedEventArgs> GenerateDocumentCompleted;
    
    public event System.EventHandler<DistribuirDocumentacionPolizaCompletedEventArgs> DistribuirDocumentacionPolizaCompleted;
    
    public event System.EventHandler<GenerateReciboCompletedEventArgs> GenerateReciboCompleted;
    
    public event System.EventHandler<savePolicyFilesCompletedEventArgs> savePolicyFilesCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IGMXITService.BeginSendMail(GMXHelper.MailParameters mail, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSendMail(mail, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IGMXITService.EndSendMail(System.IAsyncResult result)
    {
        return base.Channel.EndSendMail(result);
    }
    
    private System.IAsyncResult OnBeginSendMail(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        GMXHelper.MailParameters mail = ((GMXHelper.MailParameters)(inValues[0]));
        return ((IGMXITService)(this)).BeginSendMail(mail, callback, asyncState);
    }
    
    private object[] OnEndSendMail(System.IAsyncResult result)
    {
        bool retVal = ((IGMXITService)(this)).EndSendMail(result);
        return new object[] {
                retVal};
    }
    
    private void OnSendMailCompleted(object state)
    {
        if ((this.SendMailCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.SendMailCompleted(this, new SendMailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void SendMailAsync(GMXHelper.MailParameters mail)
    {
        this.SendMailAsync(mail, null);
    }
    
    public void SendMailAsync(GMXHelper.MailParameters mail, object userState)
    {
        if ((this.onBeginSendMailDelegate == null))
        {
            this.onBeginSendMailDelegate = new BeginOperationDelegate(this.OnBeginSendMail);
        }
        if ((this.onEndSendMailDelegate == null))
        {
            this.onEndSendMailDelegate = new EndOperationDelegate(this.OnEndSendMail);
        }
        if ((this.onSendMailCompletedDelegate == null))
        {
            this.onSendMailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendMailCompleted);
        }
        base.InvokeAsync(this.onBeginSendMailDelegate, new object[] {
                    mail}, this.onEndSendMailDelegate, this.onSendMailCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IGMXITService.BeginGenerateDocument(GMXHelper.Section[] Sections, GMXHelper.DocumentPDF DocPdf, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGenerateDocument(Sections, DocPdf, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    byte[] IGMXITService.EndGenerateDocument(System.IAsyncResult result)
    {
        return base.Channel.EndGenerateDocument(result);
    }
    
    private System.IAsyncResult OnBeginGenerateDocument(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        GMXHelper.Section[] Sections = ((GMXHelper.Section[])(inValues[0]));
        GMXHelper.DocumentPDF DocPdf = ((GMXHelper.DocumentPDF)(inValues[1]));
        return ((IGMXITService)(this)).BeginGenerateDocument(Sections, DocPdf, callback, asyncState);
    }
    
    private object[] OnEndGenerateDocument(System.IAsyncResult result)
    {
        byte[] retVal = ((IGMXITService)(this)).EndGenerateDocument(result);
        return new object[] {
                retVal};
    }
    
    private void OnGenerateDocumentCompleted(object state)
    {
        if ((this.GenerateDocumentCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GenerateDocumentCompleted(this, new GenerateDocumentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GenerateDocumentAsync(GMXHelper.Section[] Sections, GMXHelper.DocumentPDF DocPdf)
    {
        this.GenerateDocumentAsync(Sections, DocPdf, null);
    }
    
    public void GenerateDocumentAsync(GMXHelper.Section[] Sections, GMXHelper.DocumentPDF DocPdf, object userState)
    {
        if ((this.onBeginGenerateDocumentDelegate == null))
        {
            this.onBeginGenerateDocumentDelegate = new BeginOperationDelegate(this.OnBeginGenerateDocument);
        }
        if ((this.onEndGenerateDocumentDelegate == null))
        {
            this.onEndGenerateDocumentDelegate = new EndOperationDelegate(this.OnEndGenerateDocument);
        }
        if ((this.onGenerateDocumentCompletedDelegate == null))
        {
            this.onGenerateDocumentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGenerateDocumentCompleted);
        }
        base.InvokeAsync(this.onBeginGenerateDocumentDelegate, new object[] {
                    Sections,
                    DocPdf}, this.onEndGenerateDocumentDelegate, this.onGenerateDocumentCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IGMXITService.BeginDistribuirDocumentacionPoliza(
                string MailType, 
                bool oficinaMex, 
                string PVL, 
                string NoPoliza, 
                GMXHelper.Destinatario[] asegurado, 
                GMXHelper.Destinatario[] agente, 
                GMXHelper.Destinatario[] suscriptor, 
                GMXHelper.Destinatario[] nicho, 
                GMXHelper.Destinatario[] DDP, 
                GMXHelper.FilePropertiesManager archivoCotizacion, 
                GMXHelper.FilePropertiesManager folletoCotizacion, 
                GMXHelper.FilePropertiesManager caratulaPoliza, 
                GMXHelper.FilePropertiesManager slipCompra, 
                GMXHelper.FilePropertiesManager controlPago, 
                GMXHelper.FilePropertiesManager condicionesGenerales, 
                GMXHelper.FilePropertiesManager[] FolletoPoliza, 
                System.AsyncCallback callback, 
                object asyncState)
    {
        return base.Channel.BeginDistribuirDocumentacionPoliza(MailType, oficinaMex, PVL, NoPoliza, asegurado, agente, suscriptor, nicho, DDP, archivoCotizacion, folletoCotizacion, caratulaPoliza, slipCompra, controlPago, condicionesGenerales, FolletoPoliza, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IGMXITService.EndDistribuirDocumentacionPoliza(System.IAsyncResult result)
    {
        return base.Channel.EndDistribuirDocumentacionPoliza(result);
    }
    
    private System.IAsyncResult OnBeginDistribuirDocumentacionPoliza(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string MailType = ((string)(inValues[0]));
        bool oficinaMex = ((bool)(inValues[1]));
        string PVL = ((string)(inValues[2]));
        string NoPoliza = ((string)(inValues[3]));
        GMXHelper.Destinatario[] asegurado = ((GMXHelper.Destinatario[])(inValues[4]));
        GMXHelper.Destinatario[] agente = ((GMXHelper.Destinatario[])(inValues[5]));
        GMXHelper.Destinatario[] suscriptor = ((GMXHelper.Destinatario[])(inValues[6]));
        GMXHelper.Destinatario[] nicho = ((GMXHelper.Destinatario[])(inValues[7]));
        GMXHelper.Destinatario[] DDP = ((GMXHelper.Destinatario[])(inValues[8]));
        GMXHelper.FilePropertiesManager archivoCotizacion = ((GMXHelper.FilePropertiesManager)(inValues[9]));
        GMXHelper.FilePropertiesManager folletoCotizacion = ((GMXHelper.FilePropertiesManager)(inValues[10]));
        GMXHelper.FilePropertiesManager caratulaPoliza = ((GMXHelper.FilePropertiesManager)(inValues[11]));
        GMXHelper.FilePropertiesManager slipCompra = ((GMXHelper.FilePropertiesManager)(inValues[12]));
        GMXHelper.FilePropertiesManager controlPago = ((GMXHelper.FilePropertiesManager)(inValues[13]));
        GMXHelper.FilePropertiesManager condicionesGenerales = ((GMXHelper.FilePropertiesManager)(inValues[14]));
        GMXHelper.FilePropertiesManager[] FolletoPoliza = ((GMXHelper.FilePropertiesManager[])(inValues[15]));
        return ((IGMXITService)(this)).BeginDistribuirDocumentacionPoliza(MailType, oficinaMex, PVL, NoPoliza, asegurado, agente, suscriptor, nicho, DDP, archivoCotizacion, folletoCotizacion, caratulaPoliza, slipCompra, controlPago, condicionesGenerales, FolletoPoliza, callback, asyncState);
    }
    
    private object[] OnEndDistribuirDocumentacionPoliza(System.IAsyncResult result)
    {
        bool retVal = ((IGMXITService)(this)).EndDistribuirDocumentacionPoliza(result);
        return new object[] {
                retVal};
    }
    
    private void OnDistribuirDocumentacionPolizaCompleted(object state)
    {
        if ((this.DistribuirDocumentacionPolizaCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.DistribuirDocumentacionPolizaCompleted(this, new DistribuirDocumentacionPolizaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void DistribuirDocumentacionPolizaAsync(
                string MailType, 
                bool oficinaMex, 
                string PVL, 
                string NoPoliza, 
                GMXHelper.Destinatario[] asegurado, 
                GMXHelper.Destinatario[] agente, 
                GMXHelper.Destinatario[] suscriptor, 
                GMXHelper.Destinatario[] nicho, 
                GMXHelper.Destinatario[] DDP, 
                GMXHelper.FilePropertiesManager archivoCotizacion, 
                GMXHelper.FilePropertiesManager folletoCotizacion, 
                GMXHelper.FilePropertiesManager caratulaPoliza, 
                GMXHelper.FilePropertiesManager slipCompra, 
                GMXHelper.FilePropertiesManager controlPago, 
                GMXHelper.FilePropertiesManager condicionesGenerales, 
                GMXHelper.FilePropertiesManager[] FolletoPoliza)
    {
        this.DistribuirDocumentacionPolizaAsync(MailType, oficinaMex, PVL, NoPoliza, asegurado, agente, suscriptor, nicho, DDP, archivoCotizacion, folletoCotizacion, caratulaPoliza, slipCompra, controlPago, condicionesGenerales, FolletoPoliza, null);
    }
    
    public void DistribuirDocumentacionPolizaAsync(
                string MailType, 
                bool oficinaMex, 
                string PVL, 
                string NoPoliza, 
                GMXHelper.Destinatario[] asegurado, 
                GMXHelper.Destinatario[] agente, 
                GMXHelper.Destinatario[] suscriptor, 
                GMXHelper.Destinatario[] nicho, 
                GMXHelper.Destinatario[] DDP, 
                GMXHelper.FilePropertiesManager archivoCotizacion, 
                GMXHelper.FilePropertiesManager folletoCotizacion, 
                GMXHelper.FilePropertiesManager caratulaPoliza, 
                GMXHelper.FilePropertiesManager slipCompra, 
                GMXHelper.FilePropertiesManager controlPago, 
                GMXHelper.FilePropertiesManager condicionesGenerales, 
                GMXHelper.FilePropertiesManager[] FolletoPoliza, 
                object userState)
    {
        if ((this.onBeginDistribuirDocumentacionPolizaDelegate == null))
        {
            this.onBeginDistribuirDocumentacionPolizaDelegate = new BeginOperationDelegate(this.OnBeginDistribuirDocumentacionPoliza);
        }
        if ((this.onEndDistribuirDocumentacionPolizaDelegate == null))
        {
            this.onEndDistribuirDocumentacionPolizaDelegate = new EndOperationDelegate(this.OnEndDistribuirDocumentacionPoliza);
        }
        if ((this.onDistribuirDocumentacionPolizaCompletedDelegate == null))
        {
            this.onDistribuirDocumentacionPolizaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDistribuirDocumentacionPolizaCompleted);
        }
        base.InvokeAsync(this.onBeginDistribuirDocumentacionPolizaDelegate, new object[] {
                    MailType,
                    oficinaMex,
                    PVL,
                    NoPoliza,
                    asegurado,
                    agente,
                    suscriptor,
                    nicho,
                    DDP,
                    archivoCotizacion,
                    folletoCotizacion,
                    caratulaPoliza,
                    slipCompra,
                    controlPago,
                    condicionesGenerales,
                    FolletoPoliza}, this.onEndDistribuirDocumentacionPolizaDelegate, this.onDistribuirDocumentacionPolizaCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IGMXITService.BeginGenerateRecibo(GMXHelper.EmisionPago emisionPago, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGenerateRecibo(emisionPago, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    byte[] IGMXITService.EndGenerateRecibo(System.IAsyncResult result)
    {
        return base.Channel.EndGenerateRecibo(result);
    }
    
    private System.IAsyncResult OnBeginGenerateRecibo(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        GMXHelper.EmisionPago emisionPago = ((GMXHelper.EmisionPago)(inValues[0]));
        return ((IGMXITService)(this)).BeginGenerateRecibo(emisionPago, callback, asyncState);
    }
    
    private object[] OnEndGenerateRecibo(System.IAsyncResult result)
    {
        byte[] retVal = ((IGMXITService)(this)).EndGenerateRecibo(result);
        return new object[] {
                retVal};
    }
    
    private void OnGenerateReciboCompleted(object state)
    {
        if ((this.GenerateReciboCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GenerateReciboCompleted(this, new GenerateReciboCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GenerateReciboAsync(GMXHelper.EmisionPago emisionPago)
    {
        this.GenerateReciboAsync(emisionPago, null);
    }
    
    public void GenerateReciboAsync(GMXHelper.EmisionPago emisionPago, object userState)
    {
        if ((this.onBeginGenerateReciboDelegate == null))
        {
            this.onBeginGenerateReciboDelegate = new BeginOperationDelegate(this.OnBeginGenerateRecibo);
        }
        if ((this.onEndGenerateReciboDelegate == null))
        {
            this.onEndGenerateReciboDelegate = new EndOperationDelegate(this.OnEndGenerateRecibo);
        }
        if ((this.onGenerateReciboCompletedDelegate == null))
        {
            this.onGenerateReciboCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGenerateReciboCompleted);
        }
        base.InvokeAsync(this.onBeginGenerateReciboDelegate, new object[] {
                    emisionPago}, this.onEndGenerateReciboDelegate, this.onGenerateReciboCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IGMXITService.BeginsavePolicyFiles(string condGralesNombre, byte[] condGrales, string condPartNombre, byte[] condPart, string numeroPolizaPVL, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginsavePolicyFiles(condGralesNombre, condGrales, condPartNombre, condPart, numeroPolizaPVL, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IGMXITService.EndsavePolicyFiles(System.IAsyncResult result)
    {
        return base.Channel.EndsavePolicyFiles(result);
    }
    
    private System.IAsyncResult OnBeginsavePolicyFiles(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string condGralesNombre = ((string)(inValues[0]));
        byte[] condGrales = ((byte[])(inValues[1]));
        string condPartNombre = ((string)(inValues[2]));
        byte[] condPart = ((byte[])(inValues[3]));
        string numeroPolizaPVL = ((string)(inValues[4]));
        return ((IGMXITService)(this)).BeginsavePolicyFiles(condGralesNombre, condGrales, condPartNombre, condPart, numeroPolizaPVL, callback, asyncState);
    }
    
    private object[] OnEndsavePolicyFiles(System.IAsyncResult result)
    {
        bool retVal = ((IGMXITService)(this)).EndsavePolicyFiles(result);
        return new object[] {
                retVal};
    }
    
    private void OnsavePolicyFilesCompleted(object state)
    {
        if ((this.savePolicyFilesCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.savePolicyFilesCompleted(this, new savePolicyFilesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void savePolicyFilesAsync(string condGralesNombre, byte[] condGrales, string condPartNombre, byte[] condPart, string numeroPolizaPVL)
    {
        this.savePolicyFilesAsync(condGralesNombre, condGrales, condPartNombre, condPart, numeroPolizaPVL, null);
    }
    
    public void savePolicyFilesAsync(string condGralesNombre, byte[] condGrales, string condPartNombre, byte[] condPart, string numeroPolizaPVL, object userState)
    {
        if ((this.onBeginsavePolicyFilesDelegate == null))
        {
            this.onBeginsavePolicyFilesDelegate = new BeginOperationDelegate(this.OnBeginsavePolicyFiles);
        }
        if ((this.onEndsavePolicyFilesDelegate == null))
        {
            this.onEndsavePolicyFilesDelegate = new EndOperationDelegate(this.OnEndsavePolicyFiles);
        }
        if ((this.onsavePolicyFilesCompletedDelegate == null))
        {
            this.onsavePolicyFilesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsavePolicyFilesCompleted);
        }
        base.InvokeAsync(this.onBeginsavePolicyFilesDelegate, new object[] {
                    condGralesNombre,
                    condGrales,
                    condPartNombre,
                    condPart,
                    numeroPolizaPVL}, this.onEndsavePolicyFilesDelegate, this.onsavePolicyFilesCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IGMXITService CreateChannel()
    {
        return new GMXITServiceClientChannel(this);
    }
    
    private class GMXITServiceClientChannel : ChannelBase<IGMXITService>, IGMXITService
    {
        
        public GMXITServiceClientChannel(System.ServiceModel.ClientBase<IGMXITService> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginSendMail(GMXHelper.MailParameters mail, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = mail;
            System.IAsyncResult _result = base.BeginInvoke("SendMail", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndSendMail(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("SendMail", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGenerateDocument(GMXHelper.Section[] Sections, GMXHelper.DocumentPDF DocPdf, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = Sections;
            _args[1] = DocPdf;
            System.IAsyncResult _result = base.BeginInvoke("GenerateDocument", _args, callback, asyncState);
            return _result;
        }
        
        public byte[] EndGenerateDocument(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            byte[] _result = ((byte[])(base.EndInvoke("GenerateDocument", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginDistribuirDocumentacionPoliza(
                    string MailType, 
                    bool oficinaMex, 
                    string PVL, 
                    string NoPoliza, 
                    GMXHelper.Destinatario[] asegurado, 
                    GMXHelper.Destinatario[] agente, 
                    GMXHelper.Destinatario[] suscriptor, 
                    GMXHelper.Destinatario[] nicho, 
                    GMXHelper.Destinatario[] DDP, 
                    GMXHelper.FilePropertiesManager archivoCotizacion, 
                    GMXHelper.FilePropertiesManager folletoCotizacion, 
                    GMXHelper.FilePropertiesManager caratulaPoliza, 
                    GMXHelper.FilePropertiesManager slipCompra, 
                    GMXHelper.FilePropertiesManager controlPago, 
                    GMXHelper.FilePropertiesManager condicionesGenerales, 
                    GMXHelper.FilePropertiesManager[] FolletoPoliza, 
                    System.AsyncCallback callback, 
                    object asyncState)
        {
            object[] _args = new object[16];
            _args[0] = MailType;
            _args[1] = oficinaMex;
            _args[2] = PVL;
            _args[3] = NoPoliza;
            _args[4] = asegurado;
            _args[5] = agente;
            _args[6] = suscriptor;
            _args[7] = nicho;
            _args[8] = DDP;
            _args[9] = archivoCotizacion;
            _args[10] = folletoCotizacion;
            _args[11] = caratulaPoliza;
            _args[12] = slipCompra;
            _args[13] = controlPago;
            _args[14] = condicionesGenerales;
            _args[15] = FolletoPoliza;
            System.IAsyncResult _result = base.BeginInvoke("DistribuirDocumentacionPoliza", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndDistribuirDocumentacionPoliza(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("DistribuirDocumentacionPoliza", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGenerateRecibo(GMXHelper.EmisionPago emisionPago, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = emisionPago;
            System.IAsyncResult _result = base.BeginInvoke("GenerateRecibo", _args, callback, asyncState);
            return _result;
        }
        
        public byte[] EndGenerateRecibo(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            byte[] _result = ((byte[])(base.EndInvoke("GenerateRecibo", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginsavePolicyFiles(string condGralesNombre, byte[] condGrales, string condPartNombre, byte[] condPart, string numeroPolizaPVL, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[5];
            _args[0] = condGralesNombre;
            _args[1] = condGrales;
            _args[2] = condPartNombre;
            _args[3] = condPart;
            _args[4] = numeroPolizaPVL;
            System.IAsyncResult _result = base.BeginInvoke("savePolicyFiles", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndsavePolicyFiles(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("savePolicyFiles", _args, result)));
            return _result;
        }
    }
}
