// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GMX.wspago
{
	using System.Diagnostics;
	using System;
	using System.Xml.Serialization;
	using System.ComponentModel;
	using System.Web.Services.Protocols;
	using System.Web.Services;


	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name = "PaymentCenterSoap", Namespace = "http://http://www.gmx.com.mx/")]
	public partial class PaymentCenter : System.Web.Services.Protocols.SoapHttpClientProtocol
	{

		private System.Threading.SendOrPostCallback ExecuteDirectPaymentOperationCompleted;

		private System.Threading.SendOrPostCallback MITResponseToXmlOperationCompleted;

		private System.Threading.SendOrPostCallback GetReferenceOperationCompleted;

		private System.Threading.SendOrPostCallback GetMerchantIdsOperationCompleted;

		private System.Threading.SendOrPostCallback GetMerchantIdsSucOperationCompleted;

		private System.Threading.SendOrPostCallback MITSucResponseToXmlOperationCompleted;

		private System.Threading.SendOrPostCallback ExecuteDirectPaymentSucOperationCompleted;

		/// CodeRemarks
		public PaymentCenter()
		{
			this.Url = "http://desa.gmx.com.mx/wsPagoTB/PaymentCenter.asmx";
		}

		public PaymentCenter(string url)
		{
			this.Url = url;
		}

		/// CodeRemarks
		public event ExecuteDirectPaymentCompletedEventHandler ExecuteDirectPaymentCompleted;

		/// CodeRemarks
		public event MITResponseToXmlCompletedEventHandler MITResponseToXmlCompleted;

		/// CodeRemarks
		public event GetReferenceCompletedEventHandler GetReferenceCompleted;

		/// CodeRemarks
		public event GetMerchantIdsCompletedEventHandler GetMerchantIdsCompleted;

		/// CodeRemarks
		public event GetMerchantIdsSucCompletedEventHandler GetMerchantIdsSucCompleted;

		/// CodeRemarks
		public event MITSucResponseToXmlCompletedEventHandler MITSucResponseToXmlCompleted;

		/// CodeRemarks
		public event ExecuteDirectPaymentSucCompletedEventHandler ExecuteDirectPaymentSucCompleted;

		/// CodeRemarks
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://http://www.gmx.com.mx/ExecuteDirectPayment", RequestNamespace = "http://http://www.gmx.com.mx/", ResponseNamespace = "http://http://www.gmx.com.mx/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		[return: System.Xml.Serialization.XmlElementAttribute("CENTEROFPAYMENTS", IsNullable = true)]
		public MITResponse ExecuteDirectPayment(string merchant, string reference, double amount, string currency, string cc_type, string cc_name, string cc_number, System.DateTime cc_expiry, string cc_cvv)
		{
			object[] results = this.Invoke("ExecuteDirectPayment", new object[] {
						merchant,
						reference,
						amount,
						currency,
						cc_type,
						cc_name,
						cc_number,
						cc_expiry,
						cc_cvv});
			return ((MITResponse)(results[0]));
		}

		/// CodeRemarks
		public void ExecuteDirectPaymentAsync(string merchant, string reference, double amount, string currency, string cc_type, string cc_name, string cc_number, System.DateTime cc_expiry, string cc_cvv)
		{
			this.ExecuteDirectPaymentAsync(merchant, reference, amount, currency, cc_type, cc_name, cc_number, cc_expiry, cc_cvv, null);
		}

		/// CodeRemarks
		public void ExecuteDirectPaymentAsync(string merchant, string reference, double amount, string currency, string cc_type, string cc_name, string cc_number, System.DateTime cc_expiry, string cc_cvv, object userState)
		{
			if ((this.ExecuteDirectPaymentOperationCompleted == null))
			{
				this.ExecuteDirectPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteDirectPaymentOperationCompleted);
			}
			this.InvokeAsync("ExecuteDirectPayment", new object[] {
						merchant,
						reference,
						amount,
						currency,
						cc_type,
						cc_name,
						cc_number,
						cc_expiry,
						cc_cvv}, this.ExecuteDirectPaymentOperationCompleted, userState);
		}

		private void OnExecuteDirectPaymentOperationCompleted(object arg)
		{
			if ((this.ExecuteDirectPaymentCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.ExecuteDirectPaymentCompleted(this, new ExecuteDirectPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// CodeRemarks
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://http://www.gmx.com.mx/MITResponseToXml", RequestNamespace = "http://http://www.gmx.com.mx/", ResponseNamespace = "http://http://www.gmx.com.mx/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string MITResponseToXml([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] MITResponse CENTEROFPAYMENTS)
		{
			object[] results = this.Invoke("MITResponseToXml", new object[] {
						CENTEROFPAYMENTS});
			return ((string)(results[0]));
		}

		/// CodeRemarks
		public void MITResponseToXmlAsync(MITResponse CENTEROFPAYMENTS)
		{
			this.MITResponseToXmlAsync(CENTEROFPAYMENTS, null);
		}

		/// CodeRemarks
		public void MITResponseToXmlAsync(MITResponse CENTEROFPAYMENTS, object userState)
		{
			if ((this.MITResponseToXmlOperationCompleted == null))
			{
				this.MITResponseToXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMITResponseToXmlOperationCompleted);
			}
			this.InvokeAsync("MITResponseToXml", new object[] {
						CENTEROFPAYMENTS}, this.MITResponseToXmlOperationCompleted, userState);
		}

		private void OnMITResponseToXmlOperationCompleted(object arg)
		{
			if ((this.MITResponseToXmlCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.MITResponseToXmlCompleted(this, new MITResponseToXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// CodeRemarks
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://http://www.gmx.com.mx/GetReference", RequestNamespace = "http://http://www.gmx.com.mx/", ResponseNamespace = "http://http://www.gmx.com.mx/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string GetReference(string poliza, System.DateTime fecha, double monto)
		{
			object[] results = this.Invoke("GetReference", new object[] {
						poliza,
						fecha,
						monto});
			return ((string)(results[0]));
		}

		/// CodeRemarks
		public void GetReferenceAsync(string poliza, System.DateTime fecha, double monto)
		{
			this.GetReferenceAsync(poliza, fecha, monto, null);
		}

		/// CodeRemarks
		public void GetReferenceAsync(string poliza, System.DateTime fecha, double monto, object userState)
		{
			if ((this.GetReferenceOperationCompleted == null))
			{
				this.GetReferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReferenceOperationCompleted);
			}
			this.InvokeAsync("GetReference", new object[] {
						poliza,
						fecha,
						monto}, this.GetReferenceOperationCompleted, userState);
		}

		private void OnGetReferenceOperationCompleted(object arg)
		{
			if ((this.GetReferenceCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.GetReferenceCompleted(this, new GetReferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// CodeRemarks
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://http://www.gmx.com.mx/GetMerchantIds", RequestNamespace = "http://http://www.gmx.com.mx/", ResponseNamespace = "http://http://www.gmx.com.mx/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public KeyValue[] GetMerchantIds()
		{
			object[] results = this.Invoke("GetMerchantIds", new object[0]);
			return ((KeyValue[])(results[0]));
		}

		/// CodeRemarks
		public void GetMerchantIdsAsync()
		{
			this.GetMerchantIdsAsync(null);
		}

		/// CodeRemarks
		public void GetMerchantIdsAsync(object userState)
		{
			if ((this.GetMerchantIdsOperationCompleted == null))
			{
				this.GetMerchantIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMerchantIdsOperationCompleted);
			}
			this.InvokeAsync("GetMerchantIds", new object[0], this.GetMerchantIdsOperationCompleted, userState);
		}

		private void OnGetMerchantIdsOperationCompleted(object arg)
		{
			if ((this.GetMerchantIdsCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.GetMerchantIdsCompleted(this, new GetMerchantIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// CodeRemarks
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://http://www.gmx.com.mx/GetMerchantIdsSuc", RequestNamespace = "http://http://www.gmx.com.mx/", ResponseNamespace = "http://http://www.gmx.com.mx/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public beMitSettings[] GetMerchantIdsSuc(int App)
		{
			object[] results = this.Invoke("GetMerchantIdsSuc", new object[] {
						App});
			return ((beMitSettings[])(results[0]));
		}

		/// CodeRemarks
		public void GetMerchantIdsSucAsync(int App)
		{
			this.GetMerchantIdsSucAsync(App, null);
		}

		/// CodeRemarks
		public void GetMerchantIdsSucAsync(int App, object userState)
		{
			if ((this.GetMerchantIdsSucOperationCompleted == null))
			{
				this.GetMerchantIdsSucOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMerchantIdsSucOperationCompleted);
			}
			this.InvokeAsync("GetMerchantIdsSuc", new object[] {
						App}, this.GetMerchantIdsSucOperationCompleted, userState);
		}

		private void OnGetMerchantIdsSucOperationCompleted(object arg)
		{
			if ((this.GetMerchantIdsSucCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.GetMerchantIdsSucCompleted(this, new GetMerchantIdsSucCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// CodeRemarks
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://http://www.gmx.com.mx/MITSucResponseToXml", RequestNamespace = "http://http://www.gmx.com.mx/", ResponseNamespace = "http://http://www.gmx.com.mx/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string MITSucResponseToXml([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] MITResponse CENTEROFPAYMENTS)
		{
			object[] results = this.Invoke("MITSucResponseToXml", new object[] {
						CENTEROFPAYMENTS});
			return ((string)(results[0]));
		}

		/// CodeRemarks
		public void MITSucResponseToXmlAsync(MITResponse CENTEROFPAYMENTS)
		{
			this.MITSucResponseToXmlAsync(CENTEROFPAYMENTS, null);
		}

		/// CodeRemarks
		public void MITSucResponseToXmlAsync(MITResponse CENTEROFPAYMENTS, object userState)
		{
			if ((this.MITSucResponseToXmlOperationCompleted == null))
			{
				this.MITSucResponseToXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMITSucResponseToXmlOperationCompleted);
			}
			this.InvokeAsync("MITSucResponseToXml", new object[] {
						CENTEROFPAYMENTS}, this.MITSucResponseToXmlOperationCompleted, userState);
		}

		private void OnMITSucResponseToXmlOperationCompleted(object arg)
		{
			if ((this.MITSucResponseToXmlCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.MITSucResponseToXmlCompleted(this, new MITSucResponseToXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// CodeRemarks
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://http://www.gmx.com.mx/ExecuteDirectPaymentSuc", RequestNamespace = "http://http://www.gmx.com.mx/", ResponseNamespace = "http://http://www.gmx.com.mx/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		[return: System.Xml.Serialization.XmlElementAttribute("CENTEROFPAYMENTS", IsNullable = true)]
		public MITResponse ExecuteDirectPaymentSuc(string merchant, string reference, double amount, string currency, string cc_type, string cc_name, string cc_number, System.DateTime cc_expiry, string cc_cvv, int App)
		{
			object[] results = this.Invoke("ExecuteDirectPaymentSuc", new object[] {
						merchant,
						reference,
						amount,
						currency,
						cc_type,
						cc_name,
						cc_number,
						cc_expiry,
						cc_cvv,
						App});
			return ((MITResponse)(results[0]));
		}

		/// CodeRemarks
		public void ExecuteDirectPaymentSucAsync(string merchant, string reference, double amount, string currency, string cc_type, string cc_name, string cc_number, System.DateTime cc_expiry, string cc_cvv, int App)
		{
			this.ExecuteDirectPaymentSucAsync(merchant, reference, amount, currency, cc_type, cc_name, cc_number, cc_expiry, cc_cvv, App, null);
		}

		/// CodeRemarks
		public void ExecuteDirectPaymentSucAsync(string merchant, string reference, double amount, string currency, string cc_type, string cc_name, string cc_number, System.DateTime cc_expiry, string cc_cvv, int App, object userState)
		{
			if ((this.ExecuteDirectPaymentSucOperationCompleted == null))
			{
				this.ExecuteDirectPaymentSucOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteDirectPaymentSucOperationCompleted);
			}
			this.InvokeAsync("ExecuteDirectPaymentSuc", new object[] {
						merchant,
						reference,
						amount,
						currency,
						cc_type,
						cc_name,
						cc_number,
						cc_expiry,
						cc_cvv,
						App}, this.ExecuteDirectPaymentSucOperationCompleted, userState);
		}

		private void OnExecuteDirectPaymentSucOperationCompleted(object arg)
		{
			if ((this.ExecuteDirectPaymentSucCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.ExecuteDirectPaymentSucCompleted(this, new ExecuteDirectPaymentSucCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// CodeRemarks
		public new void CancelAsync(object userState)
		{
			base.CancelAsync(userState);
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://http://www.gmx.com.mx/")]
	public partial class MITResponse
	{

		/// <remarks/>
		public string reference;

		/// <remarks/>
		public string response;

		/// <remarks/>
		public string foliocpagos;

		/// <remarks/>
		public string auth;

		/// <remarks/>
		public string cd_response;

		/// <remarks/>
		public string cd_error;

		/// <remarks/>
		public string nb_error;

		/// <remarks/>
		public string nb_company;

		/// <remarks/>
		public string nb_merchant;

		/// <remarks/>
		public string nb_street;

		/// <remarks/>
		public string cc_type;

		/// <remarks/>
		public string tp_operation;

		/// <remarks/>
		public string cc_name;

		/// <remarks/>
		public string cc_number;

		/// <remarks/>
		public string cc_expmonth;

		/// <remarks/>
		public string cc_expyear;

		/// <remarks/>
		public string amount;

		/// <remarks/>
		public string voucher;

		/// <remarks/>
		public string tokenb5;

		/// <remarks/>
		public string tokenb6;

		/// <remarks/>
		public string voucher_comercio;

		/// <remarks/>
		public string voucher_cliente;

		/// <remarks/>
		public string friendly_response;

		/// <remarks/>
		public string emv_key_date;

		/// <remarks/>
		public string icc_csn;

		/// <remarks/>
		public string icc_atc;

		/// <remarks/>
		public string icc_arpc;

		/// <remarks/>
		public string icc_issuer_script;

		/// <remarks/>
		public string authorized_amount;

		/// <remarks/>
		public string account_balance_1;
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://http://www.gmx.com.mx/")]
	public partial class beMitSettings
	{

		/// <remarks/>
		public string ID_BRANCH;

		/// <remarks/>
		public string ID_COMPANY;

		/// <remarks/>
		public string COUNTRY;

		/// <remarks/>
		public string USER;

		/// <remarks/>
		public string PWD;

		/// <remarks/>
		public string TP_OPERATION;

		/// <remarks/>
		public string CRYPT_SEED;

		/// <remarks/>
		public string CRYPTO;

		/// <remarks/>
		public string URL_VENTA_DIRECTA;

		/// <remarks/>
		public string URL_CANCELACION;

		/// <remarks/>
		public string URL_CHECKIN;

		/// <remarks/>
		public string URL_CHECKOUT;

		/// <remarks/>
		public string URL_CIERRE_PREVENTA;

		/// <remarks/>
		public string URL_PREVENTA;

		/// <remarks/>
		public string URL_REAUTORIZACION;

		/// <remarks/>
		public string URL_REIMPRESION;

		/// <remarks/>
		public string URL_VENTA_FORZADA;

		/// <remarks/>
		public string MERCHANT_CONTADO;

		/// <remarks/>
		public string MERCHANT_3MSI;

		/// <remarks/>
		public string MERCHANT_6MSI;

		/// <remarks/>
		public string MERCHANT_USD;
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://http://www.gmx.com.mx/")]
	public partial class KeyValue
	{

		/// <remarks/>
		public string Key;

		/// <remarks/>
		public string Value;
	}

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	public delegate void ExecuteDirectPaymentCompletedEventHandler(object sender, ExecuteDirectPaymentCompletedEventArgs e);

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class ExecuteDirectPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal ExecuteDirectPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
				base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// CodeRemarks
		public MITResponse Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((MITResponse)(this.results[0]));
			}
		}
	}

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	public delegate void MITResponseToXmlCompletedEventHandler(object sender, MITResponseToXmlCompletedEventArgs e);

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class MITResponseToXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal MITResponseToXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
				base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// CodeRemarks
		public string Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((string)(this.results[0]));
			}
		}
	}

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	public delegate void GetReferenceCompletedEventHandler(object sender, GetReferenceCompletedEventArgs e);

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GetReferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal GetReferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
				base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// CodeRemarks
		public string Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((string)(this.results[0]));
			}
		}
	}

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	public delegate void GetMerchantIdsCompletedEventHandler(object sender, GetMerchantIdsCompletedEventArgs e);

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GetMerchantIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal GetMerchantIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
				base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// CodeRemarks
		public KeyValue[] Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((KeyValue[])(this.results[0]));
			}
		}
	}

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	public delegate void GetMerchantIdsSucCompletedEventHandler(object sender, GetMerchantIdsSucCompletedEventArgs e);

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GetMerchantIdsSucCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal GetMerchantIdsSucCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
				base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// CodeRemarks
		public beMitSettings[] Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((beMitSettings[])(this.results[0]));
			}
		}
	}

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	public delegate void MITSucResponseToXmlCompletedEventHandler(object sender, MITSucResponseToXmlCompletedEventArgs e);

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class MITSucResponseToXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal MITSucResponseToXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
				base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// CodeRemarks
		public string Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((string)(this.results[0]));
			}
		}
	}

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	public delegate void ExecuteDirectPaymentSucCompletedEventHandler(object sender, ExecuteDirectPaymentSucCompletedEventArgs e);

	/// CodeRemarks
	[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class ExecuteDirectPaymentSucCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal ExecuteDirectPaymentSucCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
				base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// CodeRemarks
		public MITResponse Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((MITResponse)(this.results[0]));
			}
		}
	}
}
