// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GMX {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GMX.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string RealizaCirugias {
            get {
                return ResourceManager.GetString("RealizaCirugias", resourceCulture);
            }
        }
        
        internal static string Sumaasegurada {
            get {
                return ResourceManager.GetString("Sumaasegurada", resourceCulture);
            }
        }
        
        internal static string Ejerce {
            get {
                return ResourceManager.GetString("Ejerce", resourceCulture);
            }
        }
        
        internal static string Montosexpresados {
            get {
                return ResourceManager.GetString("Montosexpresados", resourceCulture);
            }
        }
        
        internal static string Contratarcobertura {
            get {
                return ResourceManager.GetString("Contratarcobertura", resourceCulture);
            }
        }
        
        internal static string IniVig {
            get {
                return ResourceManager.GetString("IniVig", resourceCulture);
            }
        }
        
        internal static string FaltanOb {
            get {
                return ResourceManager.GetString("FaltanOb", resourceCulture);
            }
        }
    }
}
