//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMX {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMX.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Contratar la cobertura adicional RC arrendatario?.
        /// </summary>
        internal static string Contratarcobertura {
            get {
                return ResourceManager.GetString("Contratarcobertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ejerce en más de 1 lugar?.
        /// </summary>
        internal static string Ejerce {
            get {
                return ResourceManager.GetString("Ejerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan algunos campos obligatorios, revise por favor.
        /// </summary>
        internal static string FaltanOb {
            get {
                return ResourceManager.GetString("FaltanOb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de vigencia.
        /// </summary>
        internal static string IniVig {
            get {
                return ResourceManager.GetString("IniVig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifiesto  que los datos personales y profesionales son correctos y fueron verificados con el Asegurado.
        /// </summary>
        internal static string Manifiesto {
            get {
                return ResourceManager.GetString("Manifiesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montos expresados en moneda nacional (M.N.).
        /// </summary>
        internal static string Montosexpresados {
            get {
                return ResourceManager.GetString("Montosexpresados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Realiza cirugías y/o métodos invasivos?.
        /// </summary>
        internal static string RealizaCirugias {
            get {
                return ResourceManager.GetString("RealizaCirugias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma asegurada en moneda nacional.
        /// </summary>
        internal static string Sumaasegurada {
            get {
                return ResourceManager.GetString("Sumaasegurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acepto términos y condiciones.
        /// </summary>
        internal static string Terminos {
            get {
                return ResourceManager.GetString("Terminos", resourceCulture);
            }
        }
    }
}
